### ISSUE TITLE
Syntax error php 5.6

### ISSUE THREAD

**Issue by songokas** [Behat/Behat#702] opened 2015-01-28 13:28 UTC
```
PHP Parse error:  syntax error, unexpected 'as' (T_AS) in vendor/behat/behat/src/Behat/Behat/Translator/Cli/GherkinTranslationsController.php on line 55
```

```
     public function execute(InputInterface $input, OutputInterface $output)
     {
         $i18nPath = dirname(dirname(dirname(dirname(dirname(__DIR__))))) . DIRECTORY_SEPARATOR . 'i18n.php';
-
-        foreach (require($i18nPath) as $lang => $messages) {
+        $translations = require($i18nPath);
+        foreach ($translations as $lang => $messages) {
             $this->translator->addResource('array', $messages, $lang, 'output');
         }
     }
```

```
PHP 5.6.5 (cli) (built: Jan 22 2015 18:29:09) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by stof** [comment] 2015-01-30 04:58
This looks like a BC break in PHP 5.6

**Comment by everzet** [comment] 2015-02-04 08:33
Woah :/

**Comment by mvhirsch** [comment] 2015-11-11 08:47
I don't see any BC break withing PHP 5.6 in the code above.
I'm also unable to reproduce the bug with 149f8881a1df56496c37094f32d05b53e0cde37b

```
PHP 5.6.15 (cli) (built: Oct 29 2015 15:10:18) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
    with blackfire v1.6.0, https://blackfire.io, by Blackfireio Inc.
```

@songokas can you still reproduce the error?

**Comment by everzet** [comment] 2015-12-30 13:14
I'm closing this issue as it is seems to be very old and might as well have been fixed. Please reopen with updated stats if that's not the case!

**Closed by everzet** 2015-12-30 13:14 UTC
