### ISSUE TITLE
Argument transforms not working inside table

### ISSUE THREAD

**Issue by MartijnBraam** [Behat/Behat#777] opened 2015-08-17 12:18 UTC
For example:

```gherkin
Scenario Outline: Test
    Given A node exists with date "<date>"
    Then Something with relative dates should happen

Example:
| date                    |
| 2 workdays ago |
| 5 workdays ago |
```

Does not run my transformer:

```php
  /**
   * @Transform :days workdays ago
   */
  public function castNegativeWorkdays($days) {
    stuff...
  }
```

The transformer is working fine when using it as a non-table value

**Comment by ciaranmcnulty** [comment] 2015-08-17 12:37
Does this work when the placeholder in the Transform is `:date` ?

**Comment by MartijnBraam** [comment] 2015-08-17 12:41
That doesn't change the result.

**Comment by stof** [comment] 2015-08-17 13:05
@MartijnBraam can you show the scenario you wrote for the working case ?

**Comment by MartijnBraam** [comment] 2015-08-17 13:56
I'm using behat with the drupal-extension. This is a working scenario:

```gherkin
  @api
  Scenario: Test the date status
    Given I am viewing a "Dossier":
      | title          | Test dossier         |
      | field_stage    | Request acknowledged |
      | field_due_date | 3 workdays ago       |
```

the 3 workdays ago is replaced with a datetime object

**Comment by aaa2000** [comment] 2016-01-02 22:33
I think that the bug has been fixed with #540, what version do you use? The version 3.0.8 should fix that.

**Comment by everzet** [comment] 2016-01-04 15:18
@MartijnBraam could you confirm that RC1 still has this bug for you?

**Comment by MartijnBraam** [comment] 2016-01-04 18:31
@everzet I no longer have access to the codebase that has the bug. Maybe @clemens-tolboom can test it.

**Comment by everzet** [comment] 2016-01-07 12:50
@clemens-tolboom ?

**Comment by clemens-tolboom** [comment] 2016-01-07 12:53
I will check this next week.

**Comment by everzet** [comment] 2016-01-08 14:17
@clemens-tolboom thank you!

**Comment by kerasai** [comment] 2016-01-29 23:07
Using the `@Transform` tag does not seem to be working for me to operate on values in tables. I have not attempted this with an examples table for a scenario outline.

```php
  /**
   * Tokenize parameters.
   *
   * @Transform /(.*)/
   *
   * @param string $param
   *   The parameter before tokenization.
   *
   * @return string
   *   The tokenized parameter.
   */
  public function tokenize($param) {
    return strtr($param, $this->tokens);
  }
```

I understand that this is not exactly how this was intended to be done, but it seems reasonable. Any thoughts or tips?

**Comment by everzet** [comment] 2016-02-15 08:02
@kerasai transform for tables works differently. This is a separate issue.

**Comment by everzet** [comment] 2016-02-15 08:02
@clemens-tolboom any news?

**Comment by clemens-tolboom** [comment] 2016-02-15 09:00
@everzet sorry ... no time in the foreseeable future :(

**Comment by Taluu** [comment] 2016-02-15 12:20
I also had the problem with transformations inside a `PyStringNode`. cf #794

**Comment by ppaulis** [comment] 2016-05-11 11:34
@everzet I reproduced this using v3.1.0. For testing purposes, I tried to transform (true|false) into a boolean.

**Closed** 2016-08-01 19:48 UTC
Labels: bug, clarification

**Comment by wcjr** [comment] 2017-03-17 14:38
@everzet @kerasai , is there already an issue opened for tables?

I'm using `^3.3.0` and my transforms are not running on tables.

**Comment by kerasai** [comment] 2017-03-17 14:53
@wcjr as far as I know, it's just not possible to make the transform `TableNode` or `PyStringNode` arguments.

I forget exactly what I did, can't find the code, but somehow I was able to hook into Behat and alter the arguments before it sent them thru to the context that analyzes the step. That's where I applied the replacement.

**Comment by wcjr** [comment] 2017-03-17 14:59
ok, that sounds really good if you happen to find it, please pass along.  For now, I'm just going to have to do this in the `TableNode` loop:

```
    private function transformNULLs($value)
    {
        return ($value === "NULL") ? NULL : $value;
    }
```

It's getting the job done but obviously not very elegant.
