### ISSUE TITLE
Can not use BEHAT_PARAMS variable to set parameters to individual items in suites>default>contexts>[individual item]

### ISSUE THREAD

**Issue by cravecode** [Behat/Behat#983] opened 2017-01-08 21:54 UTC
Lets say I have a custom FeatureContext that accepts two constructor parameters `$dummy1` and `$dummy2`. 

```php
class FeatureContext extends RawMinkContext implements MinkAwareContext
{
  public function __construct($dummy1 = false, $dummy2 = false) {
    // Do something with the constructor values.
  }
/* ... */
}

```

To correctly set `$dummy1` and `$dummy2`, I'd do the following in my `behat.yml`:

```yml
default:
  suites:
    default:
      contexts:
        - FeatureContext:
             dummy1: true
             dummy2: true
```

If you commented out `dumm1` in `behat.yml`, then attempt to set it in the environment `BEHAT_PARAMS` variable like: `{"suites":{"default":{"contexts":[{"FeatureContext": {"build_number":"99"}}]}}}`, the constructor never gets the value from the `BEHAT_PARAMS` environment variable.

I'm pretty certain that's the correct JSON structure. I inspected the resulting structure from the working `behat.yml` in the `ConfigurationLoader.php` file and mimicked it.

The issue seems to come down to the fact that individual context items are cast to  `Symfony\Component\Config\Definition\VariableNode`. In the `VariableNode-> mergeValues($leftSide, $rightSide)` function, it simply `returns $rightSide`.

Excerpt from `VariableNode.php`:
```php
    /**
     * {@inheritdoc}
     */
    protected function mergeValues($leftSide, $rightSide)
    {
        return $rightSide;
    }
```

Because of this, anything defined in the `behat.yml` for `FeatureContext` will override the `BEHAT_PARAMS`, instead of merging individual items. Even if there is just one constructor parameter and it exists in the environment variable, not behat.yml. The entire context declaration from the behat.yml file is used.

FYI: I'm aware the `behat.yml` settings take precedence over the `BEHAT_PARAMS` env variable; this is not the case. 

Even if this is the expected functionality, I hope someone finds this who is having trouble. The Behat 3.x docs state the following which could be frustrating if this is not the intended functionality.
>You can set any value for any option that is available in a behat.yml file. Just provide options in JSON format.

I'd put together a PR, however, I'm not entirely sure what the appropriate solution would be.

**Comment by everzet** [comment] 2017-01-09 11:48
Context parameters are indeed not merged, but overridden between configurations.

This is expected behaviour, but it is due to the technical, not logical limitations. In other words - it works this way because I didn't figure out the better way yet. Help is greatly appreciated!

**Comment by cravecode** [comment] 2017-01-09 12:47
Thanks for the quick response and confirmation! 

I want to say it is something in how the configuration is defined to Symfony in the `configure` function of the [SuiteExtension.php](/Behat/Behat/blob/master/src/Behat/Testwork/Suite/ServiceContainer/SuiteExtension.php#L74) file.
But looking the way the tree is built, it's pretty intimidating:
```php
        $builder
            ->defaultValue(array('default' => array(
                'enabled'    => true,
                'type'       => null,
                'settings'   => array()
            )))
            ->treatNullLike(array())
            ->treatFalseLike(array())
            ->useAttributeAsKey('name')
            ->normalizeKeys(false)
            ->prototype('array')
                ->beforeNormalization()
                    ->ifTrue(function ($suite) {
                        return is_array($suite) && count($suite);
                    })
                    ->then(function ($suite) {
                        $suite['settings'] = isset($suite['settings'])
                            ? $suite['settings']
                            : array();
                        foreach ($suite as $key => $val) {
                            $suiteKeys = array('enabled', 'type', 'settings');
                            if (!in_array($key, $suiteKeys)) {
                                $suite['settings'][$key] = $val;
                                unset($suite[$key]);
                            }
                        }
                        return $suite;
                    })
                ->end()
                ->normalizeKeys(false)
                ->addDefaultsIfNotSet()
                ->treatTrueLike(array('enabled' => true))
                ->treatNullLike(array('enabled' => true))
                ->treatFalseLike(array('enabled' => false))
                ->children()
                    ->booleanNode('enabled')
                        ->info('Enables/disables suite')
                        ->defaultTrue()
                    ->end()
                    ->scalarNode('type')
                        ->info('Specifies suite type')
                        ->defaultValue(null)
                    ->end()
                    ->arrayNode('settings')
                        ->info('Specifies suite extra settings')
                        ->defaultValue(array())
                        ->useAttributeAsKey('name')
                        ->prototype('variable')->end()
                    ->end()
                ->end()
            ->end()
        ;
```

**Comment by stof** [comment] 2017-01-10 11:31
The issue is that Behat really allows anything in suite parameters. So we have no way to provide a strict configuration there.

We could build a system validating them strictly (and then allowing to merge deeper), but it would require some BC-breaking changes. Extensions would have to register explicitly the suite settings they support, and any other key would become forbidden (or silently dropped from the configuration, which is even worse IMO).

**Comment by stof** [comment] 2017-01-10 11:32
hmm, actually, due to the fact that most people use a shortcut notation for settings, we may find a BC way to handle it for them (not easy for people using the ``settings`` key explicitly). It would require some work though

**Comment by cravecode** [comment] 2017-01-10 13:17
I'm having a hard time thinking of a clean fix. Everything I've looked into results in special Context specific logic embedded in the `SuiteExtension` file. This seems nasty. 

Maybe holding off until Behat can use Symfony 3.2+ would be the best option. Then we could use environment variables inside YML files.

See: http://symfony.com/doc/current/configuration/external_parameters.html
>New in version 3.2: env() parameters were introduced in Symfony 3.2.

**Comment by bwowk** [comment] 2017-06-11 13:32
have a look at Behat/Behat#1048

**Comment by everzet** [comment] 2017-09-02 17:10
I feel like we'll have to live with this one for a while. @cravecode thanks for your thinking though :) It all matters and helps!

**Closed by everzet** 2017-09-02 17:10 UTC
Labels: feature, help welcome, requires clarification
