### ISSUE TITLE
Argument strings with leading 0s are stripped

### ISSUE THREAD

**Issue by NeilJ247** [Behat/Behat#1407] opened 2022-08-19 11:52 UTC
**Description**

Behat version is [v3.11.0](https://github.com/Behat/Behat/releases/tag/v3.11.0)

I have a custom step which checks a phone number is saved correctly to the database.

Definition
```
And my contact number is "02087599036"
```

Code
```
  /**
   * @Then my contact number is :phone
   */
  public function myContactNumberIs(string $phone)
  {
```

**Expected**

I expect that `$phone` should contain "02087599036"

**Actual**

`$phone` is stripped of the leading 0 e.g. "2087599036"

**Comment by carlos-granados** [comment] 2024-10-31 10:23
I can't reproduce this, not even on the 3.11.0 version. Closing

**Closed by carlos-granados** 2024-10-31 10:23 UTC
Labels: Bug
