### ISSUE TITLE
Step argument transformations not working

### ISSUE THREAD

**Issue by dornathal** [Behat/Behat#772] opened 2015-07-25 23:41 UTC
/**
     * @Transform :airline
     */
    public function castICAOToAirline($airline)
    {
        return AirlineQuery::create()->findOneByICAO($airline);
    }

    /**
     * @Transform :model
     */
    public function castModelToAircraftType($model)
    {
         return AircraftTypeQuery::create()->findOneByModel($model);
    }

     /**
     * @Given airline :airline owns an :model with callsign :callsign
     */
     public function newAircraftOfAirline(Airline $airline, AircraftType $model, $callsign)
    {
        $aircraft = new Aircraft();
        $aircraft->setCallsign($callsign)
            ->setAirline($airline)
            ->setAircraftType($model)
            ->save();
         return $aircraft;
    }

Doesn't work and throws 
> Catchable Fatal Error: Argument 1 passed to AirlineSteps::newAircraftOfAirline() must be an instance of Model\Airline, string given...

Using Behat 3.0.14 instead of 3.0.15 fixed it for me, so I think there must be some kind of a bug.

**Comment by everzet** [comment] 2015-12-30 12:46
Can you show me your scenario?

**Comment by aaa2000** [comment] 2016-01-08 15:57
I tried to reproduce the bug without success by using this scenario. Scenario pass on Behat 3.0.14 and 3.0.15

```
Feature: Step Arguments Transformations
  In order to follow DRY
  As a feature writer
  I need to be able to move common
  arguments transformations
  into transformation functions

  Scenario: Multiple Arguments Transformations
    Given a file named "features/multiple_arguments.feature" with:
    """
    Feature: Step Arguments
      Scenario:
        Given I am "doe" and I am a "manager" and I have an email "doe@example.com"
    """
    Given a file named "features/bootstrap/User.php" with:
    """
      <?php
      class User
      {
          private $username;
          private $age;

          public function __construct($username, $age = 20) {
              $this->username = $username;
              $this->age = $age;
          }

          public function getUsername() { return $this->username; }
          public function getAge() { return $this->age; }
      }
    """
    Given a file named "features/bootstrap/Role.php" with:
    """
          <?php
          class Role
          {
              public function __construct($name) {
                  $this->name = $name;
              }
          }
        """
    And a file named "features/bootstrap/FeatureContext.php" with:
    """
          <?php

          class FeatureContext implements Behat\Behat\Context\Context
          {
              public function __construct()
              {
                  unset($this->user);
                  unset($this->role);
                  unset($this->email);
              }

              /** @Transform :user */
              public function castToUser($username) {
                  return new User($username);
              }

              /** @Transform :role */
              public function castToRole($name) {
                  return new Role($name);
              }

             /**
               * @Given I am :user and I am a :role and I have an email :email
               */
              public function iAmUserAndIAmARole(User $user, Role $role, $email) {
                  $this->user = $user;
                  $this->role = $role;
                  $this->email = $email;
              }
          }
          """
    When I run "behat -f progress --no-colors"
    Then it should pass with:
    """
    .

    1 scenario (1 passed)
    """
```

@dornathal Can you give more information ? Or can you retry ?

**Comment by everzet** [comment] 2016-01-10 20:59
I'm closing this issue as it is seems to be very old and might as well have been fixed. Please reopen with updated stats if that's not the case!

**Closed by everzet** 2016-01-10 20:59 UTC
Labels: clarification
