### ISSUE TITLE
Behat fails when logging an exception into Monolog

### ISSUE THREAD

**Issue by jakubzapletal** [Behat/Behat#825] opened 2016-01-13 21:18 UTC
I have found the problem when logging an exception into Monolog Logger.

```php
<?php

use Behat\Behat\Context\Context;
use Behat\Behat\Context\SnippetAcceptingContext;

class FeatureContext implements Context, SnippetAcceptingContext
{
    /**
     * @When Log exception
     */
    public function logException()
    {
        $logger = new \Monolog\Logger('default');

        $path = tmpfile();
        $defaultLog = new \Monolog\Handler\StreamHandler($path, \Monolog\Logger::DEBUG);
        $logger->pushHandler($defaultLog);

        $exception = new \Exception();
        $message = "exception: " . $exception->getMessage();
        $context = [
            'exception' => $exception,
            'trace'     => $exception->getTrace()
        ];

        $logger->addInfo($message, $context);
    }
}
```
```
Feature: 1

  Scenario: 1.1
    When Log exception
```

I have got notice:
`Notice: Undefined offset: 2 in /var/www/test/vendor/behat/behat/src/Behat/Testwork/Specification/GroupedSpecificationIterator.php on line 98` 
and a fatal error:
`Fatal error: Call to a member function next() on a non-object in /var/www/test/vendor/behat/behat/src/Behat/Testwork/Specification/GroupedSpecificationIterator.php on line 98`

Any idea what could be wrong?

- no config file
- no parameters during the run
- Behat version 3.0.15
- Monolog version 1.17.2

**Comment by jakzal** [comment] 2016-01-14 08:28
Duplicate of #739. Fixed in 78edcc3495198976913ea4423e82f4b30fe32805 :)

**Closed** 2016-01-19 12:58 UTC
