### ISSUE TITLE
the regex issue with transform and outline

### ISSUE THREAD

**Issue by Gordiievskyi** [Behat/Behat#786] opened 2015-09-23 16:53 UTC
Hi guys,

Pattern below match url and transfrom it to element of array but it must not.

```
@Transform /(extra wide)$|(wide)$|(medium)$/
```

Link : http://www.sportingindex.com/search/racing-post/?tpid=6751&utm_source=RacingPost&utm_medium=RacingPost.com&utm_campaign=RPNavSpreadsLink

I've tested it here and "medium" should not be matched:https://regex101.com/

Behat 3.0.15.
PHP 5.5.13
Windows 7

BR,
Slava

**Comment by Gordiievskyi** [comment] 2015-09-25 09:04
Hi guys any thoughts ?

**Comment by everzet** [comment] 2015-12-30 12:38
Could you provide a failing test case in the Behat test suite? I want to help, but need more information.

**Comment by aaa2000** [comment] 2016-01-07 21:58
I tried to reproduce the bug without success by using this scenario

```

  Scenario: Regex Transforming on scenario outline
    Given a file named "features/regex_transform_on_scenario_outline.feature" with:
    """
      Feature: I should be able to transform values into different types for testing

      Scenario Outline: Converting different types
        Given I have the value "<value>"
        Then it should be of type "<type>"

        Examples:
            | value                                             | type       |
            |  &utm_source=RacingPost&utm_medium                | NULL       |
            |  &utm_source=RacingPost&utm_medium=RacingPost.com | string     |

      """
    And a file named "features/bootstrap/FeatureContext.php" with:
    """
      <?php

      class FeatureContext implements Behat\Behat\Context\Context
      {
          public function __construct()
          {
              unset($this->value);
          }

          /**
           * @Transform /(extra wide)$|(wide)$|(medium)$/
           */
          public function transformUrl($string)
          {
              return null;
          }

          /**
           * @Given I have the value ":value"
           */
          public function iHaveTheValue($value)
          {
              $this->value = $value;
          }

          /**
           * @Then it should be of type :type
           */
          public function itShouldBeOfType($type)
          {
              if (gettype($this->value) != $type) {
                  throw new Exception("Expected " . $type . ", got " . gettype($this->value) . " (value: " . $this->value . ")");
              }
          }
      }
      """
    When I run "behat -f progress --no-colors"
    Then it should pass with:
    """
    ....

    2 scenarios (2 passed)
    """
```

**Comment by everzet** [comment] 2016-01-08 14:35
I'm closing this issue as it is seems to be fixed. Please reopen with updated stats if that's not the case!

**Closed by everzet** 2016-01-08 14:35 UTC
Labels: clarification
