### ISSUE TITLE
Different test were executed depending the order of the tags 

### ISSUE THREAD

**Issue by mjaeggi** [Behat/Behat#766] opened 2015-06-24 19:32 UTC
*Release: 3.0.15*

I have some features tagged with ``@featureA`` and some scenarios with ``@regression``. 
When I run: `behat --tags 'featureA&&regression'`
All the test inside the featureA will be executed

When I run: `behat --tags 'regression&&featureA'`
All the test tagged as `regression` will be executed doesn't care if belong to `featureA` or not

Shouldn't be executed only the regression scenarios from the featureA? Regardless the order of the tags

**Comment by janipalsamaki** [comment] 2015-08-20 09:07
Try: `behat --tags=featureA,regression`

**Comment by everzet** [comment] 2015-12-30 12:50
I'm closing this issue as it is seems to be very old and might as well have been fixed. Please reopen with updated stats if that's not the case!

**Closed by everzet** 2015-12-30 12:50 UTC
