### ISSUE TITLE
"No specifications found at path" error when launching the tests not from project root

### ISSUE THREAD

**Issue by jcornide** [Behat/Behat#1085] opened 2017-09-30 17:00 UTC
Hi,

This happened to me with 3.4.1 version:

If I launch the test from the project root (/var/www/project/) like this:
`vagrant@dev-server:**/var/www/project**$ /var/www/project/vendor/bin/behat /var/www/project/features/api/brand/full_rest.feature --config /var/www/project/behat.yml` works as usual

BUT if I run it from a different path like /var/www instead of /var/www/project
`vagrant@dev-server:**/var/www**$ /var/www/project/vendor/bin/behat /var/www/project/features/api/brand/full_rest.feature --config /var/www/project/behat.yml`

Then I get this error
`No specifications found at path(s) /var/www/project/features/api/brand/full_rest.feature`

I replaced the 3.4 version by the 3.0 and it works again. To me this was necessary because I was getting this error when trying to execute the tests from PHP Storm.

**Comment by walterdolce** [comment] 2017-10-02 12:47
Same here. Getting the same error when running the tests from within PhpStorm.

**Comment by sebidchi** [comment] 2017-10-03 15:52
Any news?

**Comment by walterdolce** [comment] 2017-10-03 21:15
This ceased to happen for me. 

I don't recall making substantial changes to the IDE and I'm still using the latest version of Behat (`3.4.1`). IIRC, I ran `composer dumpautoload` at some point, among the many project's code changes, but I can't tell whether that was the cause of the issue resolution.

**Comment by kleijnweb** [comment] 2017-10-07 10:24
Same issue here. Works with 3.0.5, 3.4.1, not so much.

**Comment by walterdolce** [comment] 2017-10-07 21:48
Did you both update the referenced version of behat within the IDE and ran composer dumpautoload?

**Comment by kleijnweb** [comment] 2017-10-08 05:18
I'm using the CLI. Haven't done dump autoload, I'll try it, but I can't  imagine that being the issue.

My use case is a little different: I run behat from the project root, referencing a config file in a subdirectory. Both the path to the config and the feature file are relative, yet behat 3.4.1 only finds one of them. Without "paths" arguments, behat finds all the feature files just fine.

**Comment by jcornide** [comment] 2017-10-08 10:07
I tried the dumpautoload and same result. I'm using phpstorm and I copy pasted it the command phpsotrm uses. If I ran it from the project root works fine, if not I get the path errors. And anyway it has nothing to do with the IDE because as I say in the description it happens directly in the command line callen vendor/bin/behat from outside the project root

**Comment by Skullywag** [comment] 2017-10-09 13:54
If you pin behat/gherkin to version 4.4.5 and delete your behat_gherkin_cache folder from your temp folder (mine on windows was in the user/myname/appdata/local/temp folder) it will work again, see:
https://github.com/Behat/Gherkin/issues/128 for more details.

Hope that helps someone.

**Comment by SunMar** [comment] 2017-12-14 12:17
Based on information in #1076 I dug a little deeper. `PathsFilter` gets a relative path from the `FeatureNode` which doesn't resolve if your working directory is not the same as `%paths.base%`, and so it filters all features. See my comment there for more specifics.

**Comment by afilina** [comment] 2019-08-14 14:51
In case this helps someone using PHPStorm:

1. Go to Run > Edit Configuration.
1. In the Templates section, find Behat.
1. In Custom working directory, select the root of the project.
1. Delete any existing configurations in the Behat section, or update their custom working directory.

All new Behat runs will inherit config from the template.

**Comment by leymannx** [comment] 2020-01-16 10:15
I got this error when not having added any *.feature file at all.

**Comment by ciaranmcnulty** [comment] 2022-06-30 23:57
I believe this is fixed now, please re-open if not

**Closed by ciaranmcnulty** 2022-06-30 23:57 UTC
