### ISSUE TITLE
Invalid argument matching with optional arguments

### ISSUE THREAD

**Issue by zeykzso** [Behat/Behat#1099] opened 2017-11-03 11:35 UTC
Hi! I was trying to define multiple `@When` definitions for the same php function, and with different optional parameters:

```php
/**
 * Download template from page
 *
 * @When /^(?:|I )download "(?P<entity>([\w\s]+))" Data Template file$/
 * @When /^(?:|I )download "(?P<entity>([\w\s]+))" Data Template file through "(?P<importButtonLabel>([\w\s]+))" button$/
 * @When /^(?:|I )download "(?P<entity>([\w\s]+))" Data Template file with data "(?P<dataName>([\w\s\.]+))"$/
 */
public function iDownloadDataTemplateFile($entity, $importButtonLabel = null, $dataName = null)
{
    var_dump($entity);
    var_dump($importButtonLabel);
    var_dump($dataName);
}
```
When I run it with ex: 
`When I download "Products" Data Template file through "Import" button`
the values I get are:
$entity => "Products"
$importButtonLabel => "Import"
$dataName" => Products" (instead of null)

Also for with ex: 
`When I download "Products" Data Template file with data "some_data"`

I get:
$entity => "Products"
$importButtonLabel => "Products" (instead of null)
$dataName" => "some_data"

Is this a bug, or am I doing something wrong?

**Comment by spolischook** [comment] 2017-11-03 12:54
It looks like a bug
![selection_442](https://user-images.githubusercontent.com/1978331/32374519-c87823c8-c0a6-11e7-957a-39f03b4573f5.png)

**Comment by ciaranmcnulty** [comment] 2022-07-01 00:04
This needs to be confirmed in a recent version

**Comment by carlos-granados** [comment] 2024-11-04 14:37
This problem happens because the regex has an unnecessary inner nested capturing group. This makes behat find more "matches" than it would otherwise when parsing the regex and this breaks the assignation of values to the parameters. If the expressions are changed to:
```
     * @When /^(?:|I )download "(?P<entity>[\w\s]+)" Data Template file$/
     * @When /^(?:|I )download "(?P<entity>[\w\s]+)" Data Template file through "(?P<importButtonLabel>[\w\s]+)" button$/
     * @When /^(?:|I )download "(?P<entity>[\w\s]+)" Data Template file with data "(?P<dataName>[\w\s\.]+)"$/
```
(removing the parentheses around `[\w\s]+`) then all works fine

I don't think that Behat should try to handle this case because it is going to be very difficult to differentiate it from other valid inputs, so I think we should close this issue. @acoulton @ttomdewit what do you think?

Perhaps we need to make sure that the documentation mentions this as a caveat

**Comment by stof** [comment] 2024-11-04 14:46
I indeed suggest not fixing this and documenting that custom patterns needs to be careful about which capturing groups they contain.

**Comment by carlos-granados** [comment] 2024-11-04 15:21
Added this PR to document this https://github.com/Behat/docs/pull/156

**Closed** 2024-11-04 23:55 UTC
Labels: Bug, Confirmed
